# -*- coding: utf-8 -*-
"""STREAMLIT APP — CREDIT RISK EARLY WARNING SYSTEM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OEpKjJ4IRMeIQXNWm4knhEmdKZnmzrMU

# STREAMLIT APP — CREDIT RISK EARLY WARNING SYSTEM
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# -----------------------------
# PAGE CONFIG
# -----------------------------
st.set_page_config(
    page_title="Credit Risk Early Warning System",
    layout="wide"
)

st.title("🚨 Credit Risk Early Warning System")
st.write(
    "Predict early default risk and recommend proactive interventions "
    "based on customer repayment behavior."
)

# -----------------------------
# LOAD MODEL BUNDLE
# -----------------------------
@st.cache_resource
def load_model():
    bundle = joblib.load("models/gb_bundle.pkl")
    return bundle

bundle = load_model()
model = bundle["model"]

# -----------------------------
# FEATURE ORDER (CRITICAL)
# -----------------------------
FEATURE_ORDER = [
    "Average_Delinquency",
    "Max_Delinquency",
    "number_of_delinquency_months",
    "delinquency_trend",
    "avg_utilization",
    "max_utilization",
    "payment_to_bill_ratio",
    "payment_std",
    "Avg_payment",
    "bill_std",
    "Avg_bill",
    "high_utilization_flag",
    "chronic_delinquency_flag",
    "severe_delinquency_flag"
]

# -----------------------------
# SIDEBAR INPUTS
# -----------------------------
st.sidebar.header("Customer Risk Inputs")

avg_delinq = st.sidebar.slider("Average Delinquency", -2.0, 6.0, 0.0)
max_delinq = st.sidebar.slider("Max Delinquency", -2.0, 8.0, 0.0)
num_delinq_months = st.sidebar.slider("Delinquency Months", 0, 6, 0)
delinq_trend = st.sidebar.slider("Delinquency Trend", -7, 7, 0)

avg_util = st.sidebar.slider("Average Utilization", 0.0, 5.5, 0.3)
max_util = st.sidebar.slider("Max Utilization", 0.0, 11.0, 0.5)

pay_bill_ratio = st.sidebar.slider("Payment to Bill Ratio", 0.0, 5.0, 0.5)
pay_std = st.sidebar.number_input("Payment Volatility", value=1500.0)
avg_payment = st.sidebar.number_input("Average Payment", value=2500.0)

bill_std = st.sidebar.number_input("Bill Volatility", value=5000.0)
avg_bill = st.sidebar.number_input("Average Bill Amount", value=20000.0)

high_util_flag = st.sidebar.selectbox("High Utilization Flag", [0, 1])
chronic_delinq_flag = st.sidebar.selectbox("Chronic Delinquency Flag", [0, 1])
severe_delinq_flag = st.sidebar.selectbox("Severe Delinquency Flag", [0, 1])

# -----------------------------
# BUILD INPUT DATAFRAME (SAFE)
# -----------------------------
input_df = pd.DataFrame(
    [[
        avg_delinq,
        max_delinq,
        num_delinq_months,
        delinq_trend,
        avg_util,
        max_util,
        pay_bill_ratio,
        pay_std,
        avg_payment,
        bill_std,
        avg_bill,
        high_util_flag,
        chronic_delinq_flag,
        severe_delinq_flag
    ]],
    columns=FEATURE_ORDER
)

# -----------------------------
# PREDICTION
# -----------------------------
if st.button("🔍 Evaluate Risk"):
    risk_proba = model.predict_proba(input_df)[:, 1][0]

    # Risk Tier Logic
    if risk_proba >= 0.60:
        risk_tier = "🔴 High Risk"
        recommendation = (
            "Immediate intervention recommended:\n"
            "- Reduce credit exposure\n"
            "- Proactive customer outreach\n"
            "- Payment restructuring or limit freeze"
        )
    elif risk_proba >= 0.30:
        risk_tier = "🟠 Medium Risk"
        recommendation = (
            "Early warning stage:\n"
            "- Monitor repayment closely\n"
            "- Soft reminders\n"
            "- Prevent escalation"
        )
    else:
        risk_tier = "🟢 Low Risk"
        recommendation = (
            "Customer appears stable:\n"
            "- No immediate action required\n"
            "- Continue routine monitoring"
        )

    # -----------------------------
    # DISPLAY RESULTS
    # -----------------------------
    st.subheader("📊 Risk Assessment Result")

    col1, col2 = st.columns(2)

    with col1:
        st.metric("Default Probability", f"{risk_proba:.2%}")
        st.write("**Risk Tier:**", risk_tier)

    with col2:
        st.markdown("### 🛠 Recommended Action")
        st.text(recommendation)

    st.markdown("---")
    st.caption(
        "⚠️ This tool provides decision support only. "
        "Final credit decisions should follow internal policy and regulatory guidelines."
    )