# -*- coding: utf-8 -*-
"""STREAMLIT APP — CREDIT RISK EARLY WARNING SYSTEM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OEpKjJ4IRMeIQXNWm4knhEmdKZnmzrMU

# STREAMLIT APP — CREDIT RISK EARLY WARNING SYSTEM
"""

import streamlit as st
import pandas as pd
import joblib
import numpy as np

# Load model bundle
bundle = joblib.load("app/gb_bundle (1).pkl")
model = bundle["model"]
st.set_page_config(page_title="Credit Risk Early Warning System", layout="wide")

st.title("🚨 Credit Risk Early Warning System")
st.markdown("Predict default risk and assign intervention tiers")

st.sidebar.header("Customer Inputs")

def user_input():
    credit_limit = st.sidebar.slider("Credit Limit", 10000, 1000000, 200000)
    age = st.sidebar.slider("Age", 21, 75, 35)
    pay_1 = st.sidebar.selectbox("Last Month Payment Status", [-2, -1, 0, 1, 2, 3, 4])
    bill_amt = st.sidebar.number_input("Last Bill Amount", 0, 500000, 25000)
    pay_amt = st.sidebar.number_input("Last Payment Amount", 0, 500000, 20000)

    data = {
        "LIMIT_BAL": credit_limit,
        "AGE": age,
        "PAY_1": pay_1,
        "BILL_AMT1": bill_amt,
        "PAY_AMT1": pay_amt
    }

    return pd.DataFrame([data])

input_df = user_input()

st.subheader("Customer Profile")
st.write(input_df)

# Predict
risk_proba = model.predict_proba(input_df)[:, 1][0]

# Risk tier logic
if risk_proba >= 0.68:
    tier = "🔴 High Risk"
    action = "Immediate intervention / credit freeze"
elif risk_proba >= 0.42:
    tier = "🟠 Medium Risk"
    action = "Early outreach / payment reminder"
else:
    tier = "🟢 Low Risk"
    action = "No action needed"

st.subheader("Risk Assessment")
st.metric("Default Probability", f"{risk_proba:.2%}")
st.markdown(f"### Risk Tier: {tier}")
st.markdown(f"**Recommended Action:** {action}")